
REM Generate stats for example tables

ANALYZE TABLE airlines COMPUTE STATISTICS;
ANALYZE TABLE airlines COMPUTE STATISTICS FOR ALL INDEXED COLUMNS;
ANALYZE TABLE airlines COMPUTE STATISTICS FOR ALL INDEXES;

ANALYZE TABLE airports COMPUTE STATISTICS;
ANALYZE TABLE airports COMPUTE STATISTICS FOR ALL INDEXED COLUMNS;
ANALYZE TABLE airports COMPUTE STATISTICS FOR ALL INDEXES;

ANALYZE TABLE aircraft COMPUTE STATISTICS;
ANALYZE TABLE aircraft COMPUTE STATISTICS FOR ALL INDEXED COLUMNS;
ANALYZE TABLE aircraft COMPUTE STATISTICS FOR ALL INDEXES;

ANALYZE TABLE flights COMPUTE STATISTICS;
ANALYZE TABLE flights COMPUTE STATISTICS FOR ALL INDEXED COLUMNS;
ANALYZE TABLE flights COMPUTE STATISTICS FOR ALL INDEXES;

exit

